version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
  db:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  backend:
    container_name: backend
    build: .
    entrypoint: ./wait-for-it.sh db:3306 --
    command: sh -c "daphne config.asgi:application -b 0.0.0.0 -p 8000 && gunicorn config.wsgi --workers=2 -b 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/usr/src/app/
    expose:
      - "8000"
    env_file:
      - env/.env.prod
    depends_on:
      - db
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - env/.env.prod
    depends_on:
      - db
      - redis
      - backend
  nginx:
    image: nginx:1.26.1
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media/:/usr/src/app/media
      - ./static/:/usr/src/app/static
    ports:
      - "80:80"
    depends_on:
      - backend